[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "final-demo"
version = "0.1.0"
description = "Final demo project using core plugin system"
authors = [{name = "User", email = "user@example.com"}]
requires-python = ">=3.8"
dependencies = []

[tool.setuptools.packages.find]
where = ["."]

# Alternative Poetry configuration (commented out)
# [tool.poetry]
# name = "final-demo"
# version = "0.1.0"
# description = "Final demo project using core plugin system"
# authors = ["User <user@example.com>"]
# packages = [{include = "final"}]
# 
# [tool.poetry.dependencies]
# python = "^3.8"
# core-plugin-system = {path = "../core", develop = true}